# Strategy Search Configuration

# Search Settings
search:
  total_strategies: 1000000  # Target number of strategies to test
  days: 7                     # Time budget
  population_size: 16         # Strategies per generation
  generations: 200            # Evolutionary generations
  random_sample: 1000         # Additional random exploration
  parallel_models: 4          # Train N models simultaneously on RTX 5090

# Model Architecture Search Space
model:
  hidden_size: [64, 128, 256, 512]
  num_layers: [2, 4, 6, 8]
  num_heads: [4, 8, 16]
  seq_length: [30, 60, 120]
  dropout: [0.1, 0.15, 0.2, 0.25]

# Training Hyperparameters
training:
  learning_rate: [0.0001, 0.0003, 0.0005, 0.001]
  batch_size: [128, 256, 512]
  epochs: [20, 30, 50]
  weight_decay: [0.0001, 0.001, 0.01]

# Trading Strategy Parameters
strategy:
  confidence_threshold: [0.60, 0.65, 0.70, 0.75, 0.80]
  position_sizing: ['fixed', 'kelly', 'confidence']
  stop_loss_pips: [10, 15, 20, 25, 30]
  take_profit_pips: [20, 30, 40, 50, 60]
  trailing_stop: [true, false]
  risk_per_trade: [0.01, 0.02, 0.03]  # 1-3% account risk
  strategy_logic: ['simple', 'multi_signal', 'adaptive_threshold', 'trend_confirm']
  # Strategy Logic Types:
  # - simple: Model prediction only
  # - multi_signal: Model + RSI + MACD confirmation
  # - adaptive_threshold: Adjust threshold based on volatility
  # - trend_confirm: Require trend confirmation from EMAs

# Smart Labeling Configuration
labeling:
  threshold_pips: 20  # Minimum move to label (EURUSD)
  lookforward_hours: 12  # How far ahead to look for target
  method: 'forward_return'  # forward_return, swing_points, breakout
  min_atr_multiple: 1.5  # Minimum move relative to ATR
  filter_noise: true  # Filter low-confidence labels
  balance_labels: true  # Balance buy/sell samples

# Data Configuration
data:
  symbol: 'EURUSD=X'
  start_date: '2023-11-01'  # Yahoo hourly limit: ~730 days from today
  end_date: '2025-01-31'

# Cross-Validation: 5 weeks within available data range
validation:
  num_weeks: 5
  weeks_config:
    - year: 2024
      start: '2024-01-15'  # Q1 2024
      days: 7
    - year: 2024
      start: '2024-03-20'  # Q1 end
      days: 7
    - year: 2024
      start: '2024-06-03'  # Q2 2024
      days: 7
    - year: 2024
      start: '2024-09-15'  # Q3 2024
      days: 7
    - year: 2024
      start: '2024-12-01'  # Q4 2024
      days: 7

# Fitness Function Weights (must sum to 1.0)
fitness:
  sharpe_weight: 0.40
  winrate_weight: 0.30
  drawdown_weight: 0.30  # Penalize high drawdown
  min_trades: 10  # Minimum trades per week for valid strategy

# Evolutionary Algorithm
evolution:
  survival_rate: 0.25  # Keep top 25%
  mutation_rate: 0.30  # 30% chance to mutate each param
  crossover_rate: 0.50  # 50% of new population from crossover
  random_rate: 0.25    # 25% completely random (exploration)

# System Resources
resources:
  device: 'cuda'
  gpu_memory_gb: 32
  cpu_cores: 16
  checkpoint_every: 10  # Save every N generations

# Output Settings
output:
  save_top_n: 50
  report_format: 'html'
  log_level: 'INFO'
